# Generated by Django 6.1.1 on 2026-09-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
