# Generated by Django 6.1.1 on 2026-09-13 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stockin_total_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockout',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TotalStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_in', models.IntegerField(default=0)),
                ('total_out', models.IntegerField(default=0)),
                ('current_stock', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='total_stock', to='stock.potentialstock')),
            ],
        ),
    ]
