# Generated by Django 6.1.1 on 2026-09-13 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stockout_total_quantity_totalstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockout',
            name='total_quantity',
        ),
    ]
