# Generated by Django 6.1.1 on 2026-09-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_stockout_total_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialstock',
            name='hsn_code',
            field=models.IntegerField(),
        ),
    ]
