# Generated by Django 6.1.1 on 2026-09-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_potentialstock_hsn_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='total_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='totalstock',
            name='current_stock',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='totalstock',
            name='total_in',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='totalstock',
            name='total_out',
            field=models.FloatField(default=0),
        ),
    ]
